site_name: RingCentral Engage Voice Developer Guide
site_url: https://engage-voice-api-docs.rtfd.org
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/engage-voice-api-docs
docs_dir: docs
theme:
  name: ringcentral
  product_section: engage
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

plugins:
  - git-committers:
      repository: ringcentral/engage-voice-api-docs
      branch: master
  - bootstrap-tables

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.superfences:
       disable_indented_code_blocks: true
  - pymdownx.highlight

#extra_css: [extra.css]
#extra_javascript: [fonts.js]
pages:
- 'Primary':
  - 'Analytics':
    - 'Realtime Reports':
      - 'Agent Session': analytics/reports/agent-session-report.md
      - 'Global Call Type Detail': analytics/reports/global-call-type-detail-report.md
  - 'Dialing':
    # - 'Active Calls':
    #   - 'Quick start':
    #     - 'Node JS': dialing/active-calls/quick-start/node.md
    #     - 'Python': dialing/active-calls/quick-start/python.md
    #     - 'PHP': dialing/active-calls/quick-start/php.md
    # - 'Campaigns':
    #   - 'Queues':
    - 'Leads':
      - 'Quick start':
        - 'Node JS': dialing/leads/quick-start/node.md
        - 'Python': dialing/leads/quick-start/python.md
        - 'PHP': dialing/leads/quick-start/php.md
      - 'Bulk Import Leads': dialing/leads/bulk-import.md
      - 'Searching Leads': dialing/leads/search.md
  - 'Users':
    - 'Agents':
      - 'Agents': users/agents/index.md
      - 'Agent Groups': users/agents/agent-groups.md

- 'Secondary':
  - 'Using the API':
    - 'Obtaining a Token': basics/auth-ringcentral.md
    - 'Legacy Tokens': basics/auth-legacy.md
  - 'Embeddable':
    - 'Getting Started': embeddable/get-started.md
