site_name: RingCentral Engage Developer Guide
site_url: https://engage-api-docs.rtfd.org
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/engage-api-docs
docs_dir: docs
theme:
  name: moonstone
  custom_dir: 'theme/'
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

plugins:
  - git-committers:
      repository: ringcentral/engage-voice-api-docs
      branch: master
  - bootstrap-tables

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - codehilite:
      linenums: "None"

#extra_css: [extra.css]
#extra_javascript: [fonts.js]
pages:
- 'Primary':
  - 'Campaigns and Leads':
    - 'Leads':
      - 'Bulk Import Leads': voice/leads/bulk-import.md
      - 'Searching Leads': voice/leads/search.md
  - 'Reports':
    - 'Agent Sessions': voice/reports/agent-session-report-raw.md
    - 'Calls and Recordings': voice/reports/global-call-type-detail-report.md
- 'Secondary':
  - 'Using the API':
    - 'Obtaining a Token': voice/basics/auth-ringcentral.md
    - 'Legacy Tokens': voice/basics/auth-legacy.md
  - 'Embeddable': voice/embeddable/get-started.md