site_name: RingCentral Engage Voice Developer Guide
site_url: https://engage-voice-api-docs.rtfd.org
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/engage-voice-api-docs
docs_dir: docs
theme:
  name: ringcentral
  product_section: engage
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

plugins:
  - git-committers:
      repository: ringcentral/engage-voice-api-docs
      branch: master
  - bootstrap-tables

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.superfences:
       disable_indented_code_blocks: true
  - pymdownx.highlight

#extra_css: [extra.css]
#extra_javascript: [fonts.js]
pages:
- 'Primary':
  - 'Analytics':
    - 'Cloud Reports':
      - 'Call Detail': analytics/reports/call-detail-report.md
    - 'Realtime Reports':
      - 'Agent Session': analytics/reports/agent-session-report.md
      - 'Global Call Type Detail': analytics/reports/global-call-type-detail-report.md
  - 'Routing':
    - 'Queues':
      - 'Overview': routing/queues/index.md
      - 'Queues': routing/queues/queues.md
      - 'Queue Events': routing/queues/queue-events.md
      - 'Queue Groups': routing/queues/queue-groups.md
      - 'Group Skills': routing/queues/group-skills.md
  - 'Dialing':
    - 'Active Calls':
      - 'Overview': dialing/active-calls/index.md
      - 'Getting Started':
        - 'Node JS': dialing/active-calls/quick-start/node.md
        - 'PHP': dialing/active-calls/quick-start/php.md
        - 'Python': dialing/active-calls/quick-start/python.md
      #- 'List Active Calls': dialing/activecalls/list-activecalls.md
    - 'Campaigns':
      - 'Dial Groups': dialing/dial-groups.md
    - 'Leads':
      - 'Quick start':
        - 'Node JS': dialing/leads/quick-start/node.md
        - 'Python': dialing/leads/quick-start/python.md
        - 'PHP': dialing/leads/quick-start/php.md
      - 'Bulk Import Leads': dialing/leads/bulk-import.md
      - 'Searching Leads': dialing/leads/search.md
  - 'Users':
    - 'Agents':
      - 'Overview': users/agents/index.md
      - 'Agents': users/agents/agents.md
      - 'Agent Groups': users/agents/agent-groups.md
      - 'Skill Profiles': users/agents/skill-profile.md
- 'Secondary':
  - 'Using the API':
    - 'Fundamentals':
      - 'Methods, endpoints and parameters': 'basics/uris.md'
      #- 'App permissions': 'basics/permissions.md'
      #- 'Rate limits': 'basics/rate-limits.md'
    #- 'Obtaining a Token': basics/auth-ringcentral.md
    #- 'Legacy Tokens': basics/auth-legacy.md
  - 'Authentication':
    - 'Overview': authentication/index.md
    - 'RingCentral Office Token': authentication/auth-ringcentral.md
    - 'Legacy': authentication/auth-legacy.md
  - 'SDKs': sdks/index.md
  - 'Embeddable':
    - 'Getting Started': embeddable/get-started.md
